language: node_js
node_js:
  - '6'
branches:
  only:
    - '/^v[0-9]/'
before_install:
  - npm install --global yarn
install:
  - yarn install
script:
  - yarn test
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
